### ISSUE TITLE
Clase Point: Añadir método "Modificar coordenadas".

### ISSUE THREAD

**Issue by tomas-teston** [tomas-teston/IWVG.SwC.TomasTeston#1]
[Info: Modificar coordenadas](https://github.com/tomas-teston/IWVG.SwC.TomasTeston/wiki/Point#modificar-las-coordenadas)

Hito: 23/09/2018

**Comment by lelepompom** [comment]
Hola! Acabo de hacer push de la rama issue#01. ¿Paso el tiquet a 'done'?

**Comment by lelepompom** [comment]
Acabo de ver: 'realizar la fusión con la rama develop. Finalmente cerrará el ticket'.

Entonces primero debería hacer merge con develop. Espero tu ok ;)

**Comment by tomas-teston** [comment]
Hola Sandra!

Si, mezcla tus cambios con la rama `developer`. Si colocas en el comentario #[NumIssue] te asocia el commit a la issue. Se que hay otro comando para que te autocierre la issue, pero no lo recuerdo. Puedes hacer esta tarea también a mano.

**Comment by lelepompom** [comment]
En esta página explica cómo [autocerrar una issue](https://help.github.com/articles/closing-issues-using-keywords/#closing-an-issue-in-a-different-repository), pero no parece que haya funcionado. En el comentario he puesto "Closes tomas-teston/IWVG.SwC.TomasTeston#01" porque es un repo diferente

**Comment by tomas-teston** [comment]
Hola Sandra!

Ok. Te falta por mergear la rama `issue#1` con la `developer`

**Comment by tomas-teston** [comment]
Hola Sandra.

Lo que ha ocurrido con tu parte es que el merge que has hecho no lo hiciste como no-fastforward cuando has mezclado como la rama develop, por lo que hemos perdido el rastro. Además, antes de mezclar con la rama develop deberías haberte traído esa rama y haber mezclado con tus issues para comprobar que no ha habido ningún cambio que pueda entrar en conflicto con los tuyos.

Un saludo!
