### ISSUE TITLE
[User] - Remove method "isNotEmpty"

### ISSUE THREAD

**Issue by tomas-teston** [tomas-teston/IWVG.SwC.TomasTeston#11]
El método isNotEmpty es prescindible, por lo que elimínalo.

**Comment by robertome** [comment]
El metodo isEmpty(string) tambien comprueba si la cadena es null.
Si name='' no haría falta pero si name=null daría un NullPointerException en los metodos que utilizen la propiedad "name" para hacer alguna operación como "substring

**Comment by tomas-teston** [comment]
Ok, te lo podría comprar. Cierro la issue.
