### ISSUE TITLE
[User] - Remove method "isNotEmpty" in "nameToUpperCase" method.

### ISSUE THREAD

**Issue by tomas-teston** [tomas-teston/IWVG.SwC.TomasTeston#12]
No te hace falta comprobar si la variable "name" está vacía o no, ya que su único cometido es pasarlo a mayúsculas y no te daría error si está vacía.

**Comment by robertome** [comment]
El metodo isEmpty(string) tambien comprueba si la cadena es null.
Si name='' no haría falta pero si name=null daría un NullPointerException en los metodos que utilizen la propiedad "name" para hacer alguna operación como "substring
