### ISSUE TITLE
[User] - Error in return type

### ISSUE THREAD

**Issue by tomas-teston** [tomas-teston/IWVG.SwC.TomasTeston#13]
Si te fijas, en la wiki se detalla que el método "nameToUpperCase" devuelve "void", y en tu caso estás devolviendo un String. (el único cometido de esta función es convertir el nombre a mayúsculas, nada más).

**Comment by robertome** [comment]
Ok. No lo leí bien entonces.
Lo cambio para que se ajuste a la definición
