### ISSUE TITLE
Clase User: Presentar el nombre en mayúsculas

### ISSUE THREAD

**Issue by tomas-teston** [tomas-teston/IWVG.SwC.TomasTeston#3]
[Info: Presentar el nombre en mayúsculas](https://github.com/tomas-teston/IWVG.SwC.TomasTeston/wiki/User#presentar-el-nombre-en-may%C3%BAsculas)

Hito: 23/09/2018

**Comment by robertome** [comment]
issue  #3 completado

**Comment by tomas-teston** [comment]
Hola Roberto.

Te he creado nuevas issues para reparar errores.

**Comment by tomas-teston** [comment]
Te voy a detallar todo esto en nuevas issues.
