### ISSUE TITLE
Clase Fraction: Fracción equivalente.

### ISSUE THREAD

**Issue by tomas-teston** [tomas-teston/IWVG.SwC.TomasTeston#6]
[Info: Fracción equivalente](https://github.com/tomas-teston/IWVG.SwC.TomasTeston/wiki/Fraction#isequivalent)

Hito: 30/09/2018

**Comment by robertome** [comment]
issue #6 completado

**Comment by tomas-teston** [comment]
Hola Roberto.

Te he creado nuevas issues para reparar errores.

**Comment by tomas-teston** [comment]
Te voy a detallar todo esto en nuevas issues.
