### ISSUE TITLE
[User] - Restore method "Format"

### ISSUE THREAD

**Issue by tomas-teston** [tomas-teston/IWVG.SwC.TomasTeston#9]
El método "format" que creas no hace falta.

**Comment by robertome** [comment]
El método format esta desde la primera versión 'ca9d861b5b8c368ecc8c24276dd833c056cd6e44'
lo único que he hecho ha sido modificarlo.

¿Si quieres lo dejamos con la versión original?

**Comment by tomas-teston** [comment]
Si por favor, déjalo como estaba. 

Un saludo.

**Comment by robertome** [comment]
Ok. Pero si dejo la versión original el test UserTest#testNameToUpperCaseWhenNameIsNull() falla por java.lang.NullPointerException

**Comment by tomas-teston** [comment]
Hola Roberto.

No te lies, no hagas ese test. El objetivo de la práctica es más bien la gestión de ramas más que el programar. Se que habría que controlar los errores pero no te compliques por el momento y elimina también el test UserTest#testNameToUpperCaseWhenNameIsNull()
